#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'ajcrowe-supervisord',        :git => "https://github.com/ajcrowe/puppet-supervisord.git"
mod 'puppetlabs-apache'
mod 'saz-sudo'
#mod 'scalecommerce-sc_apache',    :git => "https://github.com/ScaleCommerce/puppet-sc_apache.git"
mod 'scalecommerce-sc_supervisor',:git => "http://github.com/ScaleCommerce/puppet-sc_supervisor.git"
mod 'scalecommerce-vm_config',    :git => "https://gitlab.scale.sc/scalecommerce/puppet-vm_config.git"
mod 'yo61-logrotate',             :git => "https://github.com/yo61/puppet-logrotate.git"
