stages:
  - test
  - push2github

before_script:
  - rm -f /etc/apt/sources.list.d/puppet.list
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

.job_template: &without_ioncube
  script:
  - ./test/install-$PUPPET_VERSION.sh
  - ./test/install.sh
  - "sed -i \"s/sc_apache::php::major_version:.*/sc_apache::php::major_version: '$PHP_VERSION'/\" ./test/hieradata/module.yaml"
  - sed -i '/- sc_apache::ioncube/s/^/#/g' ./test/hieradata/module.yaml
  - sed -i -r -e "s/package\('php[0-9]+\.[0-9]+-cli'\)/package('php$PHP_VERSION-cli')/g" ./test/inspec/sc_apache.rb
  - sed -i -r -e "s/should match '\^[0-9]+\.[0-9]+'/should match '^$PHP_VERSION'/g" ./test/inspec/sc_apache.rb
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb
  - inspec exec ./test/inspec/tideways.rb

.job_template: &with_ioncube
  script:
  - ./test/install-$PUPPET_VERSION.sh
  - ./test/install.sh
  - "sed -i \"s/sc_apache::php::major_version:.*/sc_apache::php::major_version: '$PHP_VERSION'/\" ./test/hieradata/module.yaml"
  - sed -i '/- sc_apache::ioncube/s/^#//g' ./test/hieradata/module.yaml
  - sed -i -r -e "s/package\('php[0-9]+\.[0-9]+-cli'\)/package('php$PHP_VERSION-cli')/g" ./test/inspec/sc_apache.rb
  - sed -i -r -e "s/should match '\^[0-9]+\.[0-9]+'/should match '^$PHP_VERSION'/g" ./test/inspec/sc_apache.rb
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb
  - inspec exec ./test/inspec/tideways.rb
  - inspec exec ./test/inspec/ioncube.rb

# focal / puppet 7
focal:5.6:puppet7:
 image: scalecommerce/focal-supervisord:1.0
 stage: test
 tags:
    - dind
 variables:
   PUPPET_VERSION: 'puppet7'
   PHP_VERSION: '5.6'
 <<: *with_ioncube

focal:7.0:puppet7:
 image: scalecommerce/focal-supervisord:1.0
 stage: test
 tags:
    - dind
 variables:
   PUPPET_VERSION: 'puppet7'
   PHP_VERSION: '7.0'
 <<: *with_ioncube

focal:7.1:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '7.1'
  <<: *with_ioncube

focal:7.2:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '7.2'
  <<: *with_ioncube

focal:7.3:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '7.3'
  <<: *with_ioncube

focal:7.4:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '7.4'
  <<: *with_ioncube

focal:8.0:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '8.0'
  <<: *without_ioncube

focal:8.1:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '8.1'
  <<: *without_ioncube

focal:8.2:puppet7:
  image: scalecommerce/focal-supervisord:1.0
  stage: test
  tags:
    - dind
  variables:
    PUPPET_VERSION: 'puppet7'
    PHP_VERSION: '8.2'
  <<: *without_ioncube

push2github:
  stage: push2github
  only:
    - master@scalecommerce/puppet-modules/puppet-sc_apache
  script:
    - git clone --mirror $CI_REPOSITORY_URL
    - cd puppet-sc_apache.git
    - git remote set-url --push origin https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_apache.git
    - git push --quiet --mirror
