image: scalecommerce/xenial:1.11

stages:
  - PHP 5.6
  - PHP 7.0
  - PHP 7.1
  - PHP 7.2
  - push2github

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

# trusty -> puppet5
trusty:5.6:puppet5:
  image: scalecommerce/base:0.6
  stage: PHP 5.6
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.0:puppet5:
  image: scalecommerce/base:0.6
  stage: PHP 7.0
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.1:puppet5:
  image: scalecommerce/base:0.6
  stage: PHP 7.1
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.2:puppet5:
  image: scalecommerce/base:0.6
  stage: PHP 7.2
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

# trusty -> puppet6
trusty:5.6:puppet6:
  image: scalecommerce/base:0.6
  stage: PHP 5.6
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.0:puppet6:
  image: scalecommerce/base:0.6
  stage: PHP 7.0
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.1:puppet6:
  image: scalecommerce/base:0.6
  stage: PHP 7.1
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

trusty:7.2:puppet6:
  image: scalecommerce/base:0.6
  stage: PHP 7.2
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

# xenial -> puppet5
xenial:5.6:puppet5:
  image: scalecommerce/xenial:1.11
  stage: PHP 5.6
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.0:puppet5:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.0
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.1:puppet5:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.1
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.2:puppet5:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.2
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

# xenial -> puppet6
xenial:5.6:puppet6:
  image: scalecommerce/xenial:1.11
  stage: PHP 5.6
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.0:puppet6:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.0
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.1:puppet6:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.1
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

xenial:7.2:puppet6:
  image: scalecommerce/xenial:1.11
  stage: PHP 7.2
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

# bionic -> puppet5
bionic:5.6:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 5.6
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.0:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.0
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.1:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.1
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.2:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.2
  script:
  - ./test/install-puppet5.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

# bionic -> puppet6
bionic:5.6:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 5.6
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.0:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.0
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.0/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.1:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.1
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.1/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

bionic:7.2:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.2
  script:
  - ./test/install-puppet6.sh
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/7.2/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_apache.git
