image: ubuntu:16.04

test:
  script:
  - apt-get update
  - apt-get -y install curl sudo puppet
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
  - ln -sf test/hiera.yaml /etc/puppet/hiera.yaml
  - ln -sf test/hiera /var/lib/hiera
  - puppet module install puppetlabs-apache
  - puppet module install puppetlabs-apt
  - puppet module install yo61-logrotate
  - ln -sf /builds/sc-puppet/puppet-sc_apache /etc/puppet/modules/sc-apache
  - puppet apply -v test/site.pp
