image: scalecommerce/base:0.6

test:5.4:
  script:
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

test:5.6:
  script:
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

test:7.0:
  script:
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb

test:7.1:
  script:
  - ./test/install.sh
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/inspec/sc_apache.rb
  - sed -i -e "s/\${php_major_version}/5.6/" ./test/hieradata/module.yaml
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb
