image: scalecommerce/xenial:1.18

stages:
#  - PHP 5.6
  - PHP 7.0
  - PHP 7.1
  - PHP 7.2
  - PHP 7.3
  - push2github

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

.job_template: &full_test
  script:
  - ./test/install-$PUPPET_VERSION.sh
  - ./test/install.sh
  - "sed -i \"s/sc_apache::php::major_version:.*/sc_apache::php::major_version: '$PHP_VERSION'/\" ./test/hieradata/module.yaml"
  - sed -i -r -e "s/package\('php[0-9]+\.[0-9]+-cli'\)/package('php$PHP_VERSION-cli')/g" ./test/inspec/sc_apache.rb
  - sed -i -r -e "s/should match '\^[0-9]+\.[0-9]+'/should match '^$PHP_VERSION'/g" ./test/inspec/sc_apache.rb
  - puppet apply -v ./test/site.pp
  - puppet apply -v ./test/site.pp
  - inspec exec ./test/inspec/sc_apache.rb
  - inspec exec ./test/inspec/tideways.rb
  - inspec exec ./test/inspec/ioncube.rb

# xenial -> puppet5
#xenial:5.6:puppet5:
#  image: scalecommerce/xenial:1.18
#  stage: PHP 5.6
#  variables:
#    PUPPET_VERSION: 'puppet5'
#    PHP_VERSION: '5.6'
#  <<: *full_test

xenial:7.0:puppet5:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.0
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.0'
  <<: *full_test

xenial:7.1:puppet5:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.1
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.1'
  <<: *full_test

xenial:7.2:puppet5:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.2
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.2'
  <<: *full_test

xenial:7.3:puppet5:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.3
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.3'
  <<: *full_test

# xenial -> puppet6
#xenial:5.6:puppet6:
#  image: scalecommerce/xenial:1.18
#  stage: PHP 5.6
#  variables:
#    PUPPET_VERSION: 'puppet6'
#    PHP_VERSION: '5.6'
#  <<: *full_test

xenial:7.0:puppet6:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.0
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.0'
  <<: *full_test

xenial:7.1:puppet6:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.1
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.1'
  <<: *full_test

xenial:7.2:puppet6:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.2
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.2'
  <<: *full_test

xenial:7.3:puppet6:
  image: scalecommerce/xenial:1.18
  stage: PHP 7.3
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.3'
  <<: *full_test

# bionic -> puppet5
#bionic:5.6:puppet5:
#  image: scalecommerce/bionic:1.0
#  stage: PHP 5.6
#  variables:
#    PUPPET_VERSION: 'puppet5'
#    PHP_VERSION: '5.6'
#  <<: *full_test

bionic:7.0:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.0
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.0'
  <<: *full_test

bionic:7.1:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.1
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.1'
  <<: *full_test

bionic:7.2:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.2
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.2'
  <<: *full_test

bionic:7.3:puppet5:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.3
  variables:
    PUPPET_VERSION: 'puppet5'
    PHP_VERSION: '7.3'
  <<: *full_test

# bionic -> puppet6
#bionic:5.6:puppet6:
#  image: scalecommerce/bionic:1.0
#  stage: PHP 5.6
#  variables:
#    PUPPET_VERSION: 'puppet6'
#    PHP_VERSION: '5.6'
#  <<: *full_test

bionic:7.0:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.0
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.0'
  <<: *full_test

bionic:7.1:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.1
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.1'
  <<: *full_test

bionic:7.2:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.2
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.2'
  <<: *full_test

bionic:7.3:puppet6:
  image: scalecommerce/bionic:1.0
  stage: PHP 7.3
  variables:
    PUPPET_VERSION: 'puppet6'
    PHP_VERSION: '7.3'
  <<: *full_test

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_apache.git
